cd ..
python run_phases.py \
  --learn 0 \
  --sigma_lr 0.01 \
  --sigma_lr_strategy adam \
  --phases 50 \
  --sigma_exponent 2.0 \
  --sigma_init 1.0 \
  --dir /Users/ale/Desktop/results/ \
  --ite 100 \
  --alg pgpe \
  --var 1.0 \
  --pol linear \
  --env swimmer \
  --horizon 100 \
  --gamma 1.0 \
  --lr 0.01 \
  --lr_strategy adam \
  --n_workers 1 \
  --batch 100 \
  --clip 0 \
  --n_trials 1 
