cd ..
python run_phases.py \
  --learn 1 \
  --sigma_lr 0.001 \
  --sigma_lr_strategy adam \
  --phases 100 \
  --sigma_exponent 2.0 \
  --sigma_init 1.0 \
  --dir /Users/ale/Desktop/results/ \
  --ite 100 \
  --alg pg \
  --var 1.0 \
  --pol linear \
  --env swimmer \
  --costs 0 \
  --horizon 100 \
  --gamma 1.0 \
  --lr 0.0001 \
  --lr_strategy adam \
  --n_workers 4 \
  --batch 100 \
  --clip 0 \
  --n_trials 1 
